spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clients
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
  mvc:
    locale: es_MX
logging:
  level:
    org.hibernate.SQL: DEBUG

